inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot


Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'
Metrics/AbcSize:
  Max: 32
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
Layout/LineLength:
  Max: 160
  Exclude:
    - config/initializers/devise.rb
    - db/migrate/*.rb
