name: reviewdog
on: [pull_request]
permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  statuses: write
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run rubocop with reviewdog
        uses: reviewdog/action-rubocop@v2.8.0
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile
          reporter: github-pr-check
  rails_best_practices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: rails_best_practices
        uses: blooper05/action-rails_best_practices@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
